parameters:

    #
    # Entities
    #
    elcodi.core.referral_program.entity.invitation.class: Elcodi\Component\ReferralProgram\Entity\Invitation
    elcodi.core.referral_program.entity.invitation_bag.class: Elcodi\Component\ReferralProgram\Entity\InvitationBag

    #
    # Factories
    #
    elcodi.factory.referral_rule.class: Elcodi\Component\ReferralProgram\Factory\ReferralRuleFactory
    elcodi.factory.referral_line.class: Elcodi\Component\ReferralProgram\Factory\ReferralLineFactory
    elcodi.factory.referral_hash.class: Elcodi\Component\ReferralProgram\Factory\ReferralHashFactory
    elcodi.factory.referral_invitation.class: Elcodi\Component\ReferralProgram\Factory\InvitationFactory
    elcodi.factory.referral_invitation_bag.class: Elcodi\Component\ReferralProgram\Factory\InvitationBagFactory

    #
    # Services
    #
    elcodi.manager.referral_program.class: Elcodi\Component\ReferralProgram\Services\ReferralProgramManager
    elcodi.manager.referral_hash.class: Elcodi\Component\ReferralProgram\Services\ReferralHashManager
    elcodi.manager.referral_route.class: Elcodi\Component\ReferralProgram\Services\ReferralRouteManager
    elcodi.manager.referral_coupon.class: Elcodi\Component\ReferralProgram\Services\ReferralCouponManager
    elcodi.manager.referral_rule.class: Elcodi\Component\ReferralProgram\Services\ReferralRuleManager

    #
    # Routes
    #
    elcodi.core.referral_program.routes.loader.class: Elcodi\Component\ReferralProgram\Router\ReferralProgramRoutesLoader

    #
    # EventListeners
    #
    elcodi.core.referral_program.event_listener.referral_program_event_listener.class: Elcodi\Component\ReferralProgram\EventListener\ReferralProgramEventListener

    #
    # Controllers
    #
    elcodi.controller.referral_program.class: Elcodi\Component\ReferralProgram\Controller\ReferralProgramController
