services:

    #
    # EventListeners
    #
    elcodi.core.referral_program.event_listener.referral_program_event_listener:
        class: %elcodi.core.referral_program.event_listener.referral_program_event_listener.class%
        arguments:
            referral_coupon_manager: @elcodi.manager.referral_coupon
            order_coupon_manager: @elcodi.manager.order_coupon
            request_stack: @request_stack
        tags:
            - { name: kernel.event_listener, event: user.register, method: onCustomerRegister }
            - { name: kernel.event_listener, event: order.oncreated, method: onOrderCreated }
