services:

    #
    # Factories
    #

    #
    # Factory for entity referral_rule
    #
    elcodi.factory.referral_rule:
        class: %elcodi.factory.referral_rule.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.referral_rule.class%"]]

    #
    # Factory for entity referral_line
    #
    elcodi.factory.referral_line:
        class: %elcodi.factory.referral_line.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.referral_line.class%"]]

    #
    # Factory for entity referral_hash
    #
    elcodi.factory.referral_hash:
        class: %elcodi.factory.referral_hash.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.referral_hash.class%"]]

    #
    # Factory for entity invitation
    #
    elcodi.factory.referral_invitation:
        class: %elcodi.factory.referral_invitation.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.invitation.class%"]]

    #
    # Factory for entity invitation_bag
    #
    elcodi.factory.referral_invitation_bag:
        class: %elcodi.factory.referral_invitation_bag.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.referral_program.entity.invitation_bag.class%"]]
