services:

    #
    # Object Managers
    #
    elcodi.object_manager.referral_hash:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.referral_program.entity.referral_hash.class% ]

    elcodi.object_manager.referral_line:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.referral_program.entity.referral_line.class% ]

    elcodi.object_manager.referral_rule:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.referral_program.entity.referral_rule.class% ]
