services:

    #
    # Repositories
    #

    #
    # Repository for entity referral_hash
    #
    elcodi.repository.referral_hash:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.referral_program.entity.referral_hash.class% ]

    #
    # Repository for entity referral_line
    #
    elcodi.repository.referral_line:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.referral_program.entity.referral_line.class% ]

    #
    # Repository for entity referral_rule
    #
    elcodi.repository.referral_rule:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.referral_program.entity.referral_rule.class% ]
