services:

    #
    # Services
    #
    elcodi.manager.referral_program:
        class: %elcodi.manager.referral_program.class%
        arguments:
            event_dispatcher: @event_dispatcher
            referral_rule_repository: @elcodi.repository.referral_rule
            referral_line_repository: @elcodi.repository.referral_line
            entity_manager: @doctrine.orm.default_entity_manager
            referral_route_manager: @elcodi.manager.referral_route
            referral_hash_manager: @elcodi.manager.referral_hash
            referral_line_factory: @elcodi.factory.referral_line
            invitation_bag_factory: @elcodi.factory.referral_invitation_bag
            invitation_factory: @elcodi.factory.referral_invitation
            customer_repository: @elcodi.repository.customer
            purge_disabled_lines: %elcodi.core.referral_program.purge_disabled_lines%
            auto_referral_assignment: %elcodi.core.referral_program.auto_referral_assignment%

    elcodi.referral_program:
        alias: elcodi.manager.referral_program

    elcodi.manager.referral_route:
        class: %elcodi.manager.referral_route.class%
        arguments:
            router: @router
            controller_route_name: %elcodi.core.referral_program.controller_route_name%

    elcodi.referral_route_manager:
        alias: elcodi.manager.referral_route

    elcodi.manager.referral_hash:
        class: %elcodi.manager.referral_hash.class%
        arguments:
            referral_hash_repository: @elcodi.repository.referral_hash
            entity_manager: @doctrine.orm.default_entity_manager
            referral_hash_generator: @elcodi.generator.sha1
            referral_hash_factory: @elcodi.factory.referral_hash

    elcodi.manager.referral_hash:
        alias: elcodi.manager.referral_hash

    elcodi.manager.referral_coupon:
        class: %elcodi.manager.referral_coupon.class%
        arguments:
            event_dispatcher: @event_dispatcher
            referral_program_manager: @elcodi.manager.referral_program
            entity_manager: @doctrine.orm.default_entity_manager
            coupon_manager: @elcodi.manager.coupon
            referral_line_repository: @elcodi.repository.referral_line
            referral_hash_manager: @elcodi.manager.referral_hash

    elcodi.manager.referral_coupon:
        alias: elcodi.manager.referral_coupon

    elcodi.manager.referral_rule:
        class: %elcodi.manager.referral_rule.class%
        arguments:
            referral_rule_repository: @elcodi.repository.referral_rule
            entity_manager: @doctrine.orm.default_entity_manager

    elcodi.manager.referral_rule:
        alias: elcodi.manager.referral_rule

    #
    # Routes
    #
    elcodi.core.referral_program.routes.loader:
        class: %elcodi.core.referral_program.routes.loader.class%
        arguments:
            controller.route.name: %elcodi.core.referral_program.controller_route_name%
            controller.route: %elcodi.core.referral_program.controller_route%
        tags:
            - { name: routing.loader }
